config/routes.rb
Rails.application.routes.draw do

    resources :melakarta

    resources :janyas

    resources :homes

    root 'welcome#index'
    get 'signup', to: 'users#new'
    post 'users', to: 'users#create'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/janya.rb
class Janya < ApplicationRecord
  belongs_to :melakartum
end

app/models/melakartum.rb
class Melakartum < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    
    def homes
    end
end

app/controllers/janyas_controller.rb
class JanyasController < ApplicationController
    def index
     @janyas = Janya.all
  end
end

app/controllers/melakarta_controller.rb
class MelakartaController < ApplicationController
  def index
     @melakarta = Melakartum.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id 
           flash[:notice] = "Logged in successfully"
         redirect_to '/homes'
        else 
            flash.now[:alert] = "There was something wrong with your login detail"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
      @user = User.new(user_params)
      if @user.save
        flash[:notice] = "Welcome to raga, you have successfully signed up"
        redirect_to '/homes'
      else
         render 'new'
      end
    end

    private 
    def user_params
      params.require(:user).permit(:username, :email, :password)    
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/janyas_helper.rb
module JanyasHelper
end

app/helpers/melakarta_helper.rb
module MelakartaHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/homes/index.html.erb
<font size="20" font face="impact" color="hotpink">Janyas and Melakartas</font>
<br>
<font size="5" font face="impact" color="darkorchid">By Siri Rao</font>


<br> 
<br>

<br>
<img src="/melakarta.jpg" />

<body style="background-color:paleturquoise;">
<body>

<h2><font face="courier" color="darkorchid">What is a melakarta raga?</h2>
<h3>A melakarta raga is a collection of fundamental musical scales in Carnatic music </h3>
<h4>Click below to see a few melakarta ragas</h4>
<%= link_to 'Melakarta', melakarta_path %>
<br>
<br>
<h2>What is a janya raga?</h2>
<h3>A janya raga is one derived from one of the 72 melakarta ragas</h3>
<h4>Click below to see a few janya ragas</h4>
<%= link_to 'Janyas', janyas_path %>



</body>

app/views/janyas/index.html.erb
<font size="20" font face="impact" color="hotpink">Melakarta List</font>
 
<table>
  <tr>
    <th><font size="5" font face="courier" color="darkorchid">Raga Name</th>
    <th><font size="5" font face="courier" color="darkorchid">Scale</th>
    <th><font size="5" font face="courier" color="darkorchid">Melakarta ID</th>
    <th></th>
  </tr>
  <body style="background-color:paleturquoise;">
  <% @janyas.each do |janya| %>
    <tr>
      <td><%= janya.raga_name %></td>
      <td><%= janya.scale %></td>
      <td><%= janya.melakartum_id %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raga</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/melakarta/index.html.erb
<font size="20" font face="impact" color="hotpink">Melakarta List</font>
 
<table>
  <tr>
    <th><font size="5" font face="courier" color="darkorchid">Name</th>
    <th><font size="5" font face="courier" color="darkorchid">Scale</th>
    <th></th>
  </tr>
  <body style="background-color:paleturquoise;">
  <% @melakarta.each do |melakartum| %>
    <tr>
      <td><%= melakartum.name %></td>
      <td><%= melakartum.scale %></td>
    </tr>
  <% end %>
</table>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<a href='/login'>
<button>Login Instead</button>
</a>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>
        
      
     
        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="form-group row">
        <%= f.label :password, class: "col-2 col-form-label text-light" %>
        <div class="col-10"> 
          <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
        </div>
      </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>

        </div>
   
      <% end %>

  

  </div>
</div>

   

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Raga</h1>
<%= render 'form' %>

app/views/welcome/index.html.erb
<font size="20" font face="impact" color="hotpink">Janyas and Melakartas</font>
<br>
<font size="5" font face="impact" color="darkorchid">By Siri Rao</font>


<a href='/login'>
<button>Login Here</button>

<a href='/signup'>
<button>Signup Here</button>


<br> 
<br>

<br>
<img src="/melakarta.jpg" />

<body style="background-color:paleturquoise;">
<body>



</body>